# Change baseurl before deploy
baseurl = "https://blog.panghuli.cn"
paginate = 5
title = "胖狐狸"

# Change it to your Disqus shortname before using
disqusShortname = "phenix3443"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage = "zh-cn"
[languages.zh-cn]
languageCode = "zh-cn"
# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true
