main:
  - identifier: home
    name: Home
    weight: 1
    url: "https://panghuli.cn/"
    params:
      icon: <i class="fas fa-home"></i>
  - identifier: blog
    name: Blog
    weight: 2
    params:
      icon: <i class="fas fa-fw fa-blog"></i>
  - name: Support
    identifier: support
    weight: 40
    params:
      description: The HBS Support Community
      icon: <i class="fas fa-fw fa-info-circle"></i>
  - name: Repository
    identifier: repository
    parent: support
    url: "https://github.com/phenix3443/blog"
    weight: 1
    params:
      icon: <i class="fab fa-fw fa-github text-primary"></i>
  - name: Bug Report
    identifier: bug-report
    parent: support
    url: >-
      https://github.com/phenix3443/blog/issues/new?template=bug_report.yml
    weight: 2
    params:
      description: Tell us about a bug or issue.
      icon: <i class="fas fa-fw fa-bug text-danger"></i>
