main:
  - name: Home
    identifier: home
    pageRef: /
    weight: 1
    params:
      icon: <i class="fas fa-home"></i>
  - name: Blog
    identifier: blog
    weight: 2
    params:
      icon: <i class="fas fa-fw fa-blog"></i>
  - name: About
    identifier: about
    pageRef: /about
    weight: 3
    params:
      icon: <i class="fas fa-info-circle"></i>
  - name: Support
    identifier: support
    weight: 40
    params:
      icon: <i class="fas fa-fw fa-question-circle"></i>
  - name: Repository
    identifier: repository
    parent: support
    url: "https://github.com/phenix3443/blog"
    weight: 1
    params:
      icon: <i class="fab fa-fw fa-github text-primary"></i>
  - name: Bug Report
    identifier: bug-report
    parent: support
    url: >-
      https://github.com/phenix3443/blog/issues/new?template=bug_report.yml
    weight: 2
    params:
      description: Tell us about a bug or issue.
      icon: <i class="fas fa-fw fa-bug text-danger"></i>
