# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
email: phenix3443
facebook: phenix3443
github: phenix3443
gitlab: phenix3443
linkedin: phenix3443
stackoverflow: phenix3443
twitter: phenix3443
# weibo:
# zhihu:
# instagram:
# quora:
# tumblr:
# reddit:
telegram: phenix3443
qq: 344300476
dockerhub: phenix3443
# bitbucket:
# kaggle:
medium: phenix3443 # Medium username or custom domain(e.g. https://custom.domain.tld).
# lastfm:
# bilibili:
# youtube: phenix3443
# discord: phenix3443
discourse: https://yourforum.tld
# facebookgroup:
# tiktok:
# pinterest:
# mastodon:
# liberapay:
paypal: phenix3443
# patreon:
# tipeee:
