main:
  - identifier: home
    name: 首页
    url: /
    weight: 1
  - identifier: archives
    name: 归档
    url: /archives/
    weight: 2
  - identifier: categories
    name: 分类
    url: /categories/
    weight: 3
  - identifier: tags
    name: 标签
    url: /tags/
    weight: 4
  - identifier: about
    name: 关于
    url: /about/
    weight: 5
