# hugo-theme-next parameters
description: phenix3443's blog.
keywords: [Hugo, Blog]

# Scheme settings
scheme: Muse
darkmode: true

# Body scrollbar settings
bodyScrollbar:
  overlay: false
  stable: true

# Mobile layout economy
mobileLayoutEconomy: true

# Theme color
themeColor:
  light: "#222"
  dark: "#222"

# Bookmark settings
bookmark:
  enable: true
  color: "#222"

# GitHub banner
githubBanner:
  enable: false

# Menu settings
menuSets:
  icons: true
  transition: true
  badges: true

# Footer settings
footer:
  since: 2016
  icon:
    name: fa fa-heart
    animated: true
    color: "#ff0000"
  beian:
    enable: false

# Font settings
font:
  enable: true

# Codeblock settings
codeblock:
  style: mac
  copyBtn: true
  maxHeight: 200


# Sidebar settings
sidebar:
  position: left
  display: post

# Social links
social:
  GitHub: https://github.com/phenix3443
  Email: mailto:phenix3443

# Post settings
post:
  toc:
    enable: true
    number: true
  copyright:
    enable: true
    license: CC BY-NC-SA 4.0
