version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - allthatnode
  - Chainlink
  - commitizen
  - faucetlink
  - oxipng
  - rcmgr
  - taskqueue
  - warnf
ignoreWords: []
import: []
